### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by bobbypaton** [MooersLab/pymolshortcuts#3]
An excellent resource - thanks for sharing!

Also thanks for adapting & acknowledging several functions we developed here at Colorado State. No biggie, but just wondering whether you could correct my name to Robert Paton (instead of Bobby Patton) in the README? 

Thanks

**Comment by MooersLab** [comment]
Thank you for the feedback and for pointing out the correction. 
The correction has been made.

Also, thank you for creating the first issue!

**Comment by bobbypaton** [comment]
Thanks again - a really great resource
